//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace search.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Schedule
    {
        public int FlID { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<int> AirCraft { get; set; }
        public Nullable<int> NetFare { get; set; }
    
        public virtual AirCraft AirCraft1 { get; set; }
        public virtual AirFare AirFare { get; set; }
    }
}
