//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace search.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARSEntities : DbContext
    {
        public ARSEntities()
            : base("name=ARSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirCraft> AirCrafts { get; set; }
        public virtual DbSet<AirFare> AirFares { get; set; }
        public virtual DbSet<Flight_Schedule> Flight_Schedule { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
    }
}
