//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirCraft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirCraft()
        {
            this.Flight_Schedule = new HashSet<Flight_Schedule>();
        }
    
        public int AcID { get; set; }
        public string AcNumber { get; set; }
        public int Capacity { get; set; }
        public string MfdBy { get; set; }
        public System.DateTime MfdOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Schedule> Flight_Schedule { get; set; }
    }
}
