//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Details
    {
        public int CnID { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public string Tel { get; set; }
        public string Street { get; set; }
        public int State { get; set; }
    
        public virtual State State1 { get; set; }
    }
}
